In [12]:
import pandas as pd 
import numpy as np
import panel as pn

pn.extension('tabulator')

import hvplot.pandas

WARNING:param.panel_extension: A HoloViz extension was loaded previously. This means the extension is already initialized and the following Panel extensions could not be properly loaded: ['tabulator']. If you are loading custom extensions with pn.extension(...) ensure that this is called before any other HoloViz extension such as hvPlot or HoloViews.

In [2]:
co2_df = pd.read_csv('https://raw.githubusercontent.com/owid/co2-data/master/owid-co2-data.csv')
# co2_df.head()

In [3]:
# datos en caché para mejorar el rendimiento del dashboard
if 'data' not in pn.state.cache.keys():
    co2_df = pd.read_csv('https://raw.githubusercontent.com/owid/co2-data/master/owid-co2-data.csv')
    pn.state.cache['data']  = co2_df.copy()
else: 
    co2_df = pn.state.cache['data']

In [4]:
co2_df.head()

,iso_code,country,year,co2,co2_per_capita,trade_co2,cement_co2,cement_co2_per_capita,coal_co2,coal_co2_per_capita,...,ghg_excluding_lucf_per_capita,methane,methane_per_capita,nitrous_oxide,nitrous_oxide_per_capita,population,gdp,primary_energy_consumption,energy_per_capita,energy_per_gdp
0,AFG,Afghanistan,1949,0.015,0.002,NaN,NaN,NaN,0.015,0.002,...,NaN,NaN,NaN,NaN,NaN,7624058.0,NaN,NaN,NaN,NaN
1,AFG,Afghanistan,1950,0.084,0.011,NaN,NaN,NaN,0.021,0.003,...,NaN,NaN,NaN,NaN,NaN,7752117.0,9.421400e+09,NaN,NaN,NaN
2,AFG,Afghanistan,1951,0.092,0.012,NaN,NaN,NaN,0.026,0.003,...,NaN,NaN,NaN,NaN,NaN,7840151.0,9.692280e+09,NaN,NaN,NaN
3,AFG,Afghanistan,1952,0.092,0.012,NaN,NaN,NaN,0.032,0.004,...,NaN,NaN,NaN,NaN,NaN,7935996.0,1.001732e+10,NaN,NaN,NaN
4,AFG,Afghanistan,1953,0.106,0.013,NaN,NaN,NaN,0.038,0.005,...,NaN,NaN,NaN,NaN,NaN,8039684.0,1.063052e+10,NaN,NaN,NaN

In [5]:
co2_df['country'].sort_values().unique()

array(['Afghanistan', 'Africa', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Anguilla', 'Antarctica', 'Antigua and Barbuda', 'Argentina',
       'Armenia', 'Aruba', 'Asia', 'Asia (excl. China & India)',
       'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain',
       'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin',
       'Bermuda', 'Bhutan', 'Bolivia', 'Bonaire Sint Eustatius and Saba',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'British Virgin Islands', 'Brunei', 'Bulgaria', 'Burkina Faso',
       'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde',
       'Central African Republic', 'Chad', 'Chile', 'China',
       'Christmas Island', 'Colombia', 'Comoros', 'Congo', 'Cook Islands',
       'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Curacao',
       'Cyprus', 'Czechia', 'Democratic Republic of Congo', 'Denmark',
       'Djibouti', 'Dominica', 'Dominican Republic', 'EU-27', 'EU-28',
       'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea',
       'Estonia', 'Eswatini', 'Ethiopia', 'Europe',
       'Europe (excl. EU-27)', 'Europe (excl. EU-28)', 'Faeroe Islands',
       'Fiji', 'Finland', 'France', 'French Equatorial Africa',
       'French Guiana', 'French Polynesia', 'French West Africa', 'Gabon',
       'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Greenland',
       'Grenada', 'Guadeloupe', 'Guatemala', 'Guinea', 'Guinea-Bissau',
       'Guyana', 'Haiti', 'Honduras', 'Hong Kong', 'Hungary', 'Iceland',
       'India', 'Indonesia', 'International transport', 'Iran', 'Iraq',
       'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan',
       'Kazakhstan', 'Kenya', 'Kiribati', 'Kosovo', 'Kuwait',
       'Kuwaiti Oil Fires', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon',
       'Leeward Islands', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein',
       'Lithuania', 'Luxembourg', 'Macao', 'Madagascar', 'Malawi',
       'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands',
       'Martinique', 'Mauritania', 'Mauritius', 'Mayotte', 'Mexico',
       'Micronesia (country)', 'Moldova', 'Mongolia', 'Montenegro',
       'Montserrat', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia',
       'Nauru', 'Nepal', 'Netherlands', 'New Caledonia', 'New Zealand',
       'Nicaragua', 'Niger', 'Nigeria', 'Niue', 'North America',
       'North America (excl. USA)', 'North Korea', 'North Macedonia',
       'Norway', 'Oceania', 'Oman', 'Pakistan', 'Palau', 'Palestine',
       'Panama', 'Panama Canal Zone', 'Papua New Guinea', 'Paraguay',
       'Peru', 'Philippines', 'Poland', 'Portugal', 'Puerto Rico',
       'Qatar', 'Reunion', 'Romania', 'Russia', 'Rwanda',
       'Ryukyu Islands', 'Saint Helena', 'Saint Kitts and Nevis',
       'Saint Lucia', 'Saint Pierre and Miquelon',
       'Saint Vincent and the Grenadines', 'Samoa',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore',
       'Sint Maarten (Dutch part)', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South America',
       'South Korea', 'South Sudan', 'Spain', 'Sri Lanka',
       'St. Kitts-Nevis-Anguilla', 'Sudan', 'Suriname', 'Sweden',
       'Switzerland', 'Syria', 'Taiwan', 'Tajikistan', 'Tanzania',
       'Thailand', 'Timor', 'Togo', 'Tonga', 'Trinidad and Tobago',
       'Tunisia', 'Turkey', 'Turkmenistan', 'Turks and Caicos Islands',
       'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates',
       'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan',
       'Vanuatu', 'Venezuela', 'Vietnam', 'Wallis and Futuna', 'World',
       'Yemen', 'Zambia', 'Zimbabwe'], dtype=object)

In [6]:
co2_df[co2_df['country'] == 'Mexico']

,iso_code,country,year,co2,co2_per_capita,trade_co2,cement_co2,cement_co2_per_capita,coal_co2,coal_co2_per_capita,...,ghg_excluding_lucf_per_capita,methane,methane_per_capita,nitrous_oxide,nitrous_oxide_per_capita,population,gdp,primary_energy_consumption,energy_per_capita,energy_per_gdp
14434,MEX,Mexico,1891,0.520,0.044,NaN,NaN,NaN,0.520,0.044,...,NaN,NaN,NaN,NaN,NaN,11781298.0,NaN,NaN,NaN,NaN
14435,MEX,Mexico,1892,0.579,0.048,NaN,NaN,NaN,0.579,0.048,...,NaN,NaN,NaN,NaN,NaN,11947763.0,NaN,NaN,NaN,NaN
14436,MEX,Mexico,1893,0.531,0.044,NaN,NaN,NaN,0.531,0.044,...,NaN,NaN,NaN,NaN,NaN,12123212.0,NaN,NaN,NaN,NaN
14437,MEX,Mexico,1894,0.539,0.044,NaN,NaN,NaN,0.539,0.044,...,NaN,NaN,NaN,NaN,NaN,12301236.0,NaN,NaN,NaN,NaN
14438,MEX,Mexico,1895,0.495,0.040,NaN,NaN,NaN,0.495,0.040,...,NaN,NaN,NaN,NaN,NaN,12481874.0,2.224889e+10,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14559,MEX,Mexico,2016,482.798,3.915,14.037,17.518,0.142,47.621,0.386,...,5.537,142.31,1.154,43.25,0.351,123333379.0,1.923887e+12,2162.618,17534.790,1.15
14560,MEX,Mexico,2017,459.849,3.685,19.805,17.960,0.144,48.530,0.389,...,5.435,144.27,1.156,43.93,0.352,124777326.0,1.964635e+12,2193.152,17576.573,NaN
14561,MEX,Mexico,2018,455.308,3.608,20.996,20.864,0.165,45.995,0.364,...,5.388,145.06,1.150,42.74,0.339,126190782.0,2.006600e+12,2175.924,17243.103,NaN
14562,MEX,Mexico,2019,435.512,3.414,19.831,20.864,0.164,43.912,0.344,...,NaN,NaN,NaN,NaN,NaN,127575529.0,NaN,2144.652,16810.783,NaN
14563,MEX,Mexico,2020,356.968,2.769,NaN,20.864,0.162,16.936,0.131,...,NaN,NaN,NaN,NaN,NaN,128932753.0,NaN,NaN,NaN,NaN

In [7]:
co2_df[co2_df['country'] == 'World']

,iso_code,country,year,co2,co2_per_capita,trade_co2,cement_co2,cement_co2_per_capita,coal_co2,coal_co2_per_capita,...,ghg_excluding_lucf_per_capita,methane,methane_per_capita,nitrous_oxide,nitrous_oxide_per_capita,population,gdp,primary_energy_consumption,energy_per_capita,energy_per_gdp
24660,OWID_WRL,World,1750,9.351,0.012,NaN,NaN,NaN,9.351,0.012,...,NaN,NaN,NaN,NaN,NaN,7.456644e+08,NaN,NaN,NaN,NaN
24661,OWID_WRL,World,1751,9.351,NaN,NaN,NaN,NaN,9.351,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24662,OWID_WRL,World,1752,9.354,NaN,NaN,NaN,NaN,9.354,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24663,OWID_WRL,World,1753,9.354,NaN,NaN,NaN,NaN,9.354,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24664,OWID_WRL,World,1754,9.358,NaN,NaN,NaN,NaN,9.358,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24926,OWID_WRL,World,2016,35452.459,4.750,-0.0,1478.758,0.198,14360.628,1.924,...,6.184,8172.01,1.095,3027.74,0.406,7.464344e+09,1.071343e+14,152944.938,20490.955,1.429
24927,OWID_WRL,World,2017,35925.738,4.760,0.0,1500.493,0.199,14453.702,1.915,...,6.197,8228.64,1.090,3078.27,0.408,7.548183e+09,1.104307e+14,155672.784,20624.761,NaN
24928,OWID_WRL,World,2018,36646.140,4.802,-0.0,1566.740,0.205,14718.145,1.929,...,6.238,8298.27,1.089,3063.75,0.402,7.631091e+09,1.136302e+14,160063.686,20975.203,NaN
24929,OWID_WRL,World,2019,36702.503,4.758,0.0,1608.472,0.208,14573.219,1.889,...,NaN,NaN,NaN,NaN,NaN,7.713468e+09,NaN,162194.290,21027.415,NaN
24930,OWID_WRL,World,2020,34807.259,4.465,0.0,1626.371,0.209,13976.098,1.793,...,NaN,NaN,NaN,NaN,NaN,7.794799e+09,NaN,NaN,NaN,NaN

### Procesamiento de datos menores

In [8]:
# Rellenar los datos faltantes (NA) con 0 y crear la columna GDP per capita
co2_df = co2_df.fillna(0)
co2_df['gdp_per_capita'] = np.where(co2_df['population']!=0, co2_df['gdp']/co2_df['population'], 0)

In [9]:
# Hacer interactivo el pipeline del dataframe
int_co2_df = co2_df.interactive()

### Emisión de CO2 a lo largo del tiempo por continente

In [10]:
# Definir los paneles de widgets
year_slider = pn.widgets.IntSlider(name='Year slider', start=1750, end=2020, step=3, value=1850)
year_slider

BokehModel(combine_events=True, render_bundle={'docs_json': {'3c4e27b3-f44a-4bdc-80c4-66e4154720aa': {'defs': …

IntSlider(end=2020, name='Year slider', start=1750, step=3, value=1850)

In [11]:
# Botones de radio para las medidas de CO2
yaxis_co2 = pn.widgets.RadioButtonGroup(
    name='Y axis',
    options=['co2', 'co2_per_capita'],
    button_type='success'
)

In [14]:
continents = ['World', 'Asia', 'Europe', 'Africa', 'North America', 'South America', 'Antarctica']

co2_pipeline =(
    int_co2_df[
        (int_co2_df.year <= year_slider) & 
        (int_co2_df.country.isin(continents))
    ]
    .groupby(['country', 'year'])[yaxis_co2].mean()
    .to_frame()
    .reset_index()
    .sort_values(by='year')
    .reset_index(drop=True)
)

In [15]:
co2_pipeline

BokehModel(combine_events=True, render_bundle={'docs_json': {'37f548d4-f0e5-4770-b65a-ee32ab737ad5': {'defs': …